relay/client/stratoschain_events.go
- qb 720: extract repeated codes in stratoschain_events.go into a single func
=> refactor/qb 720: extract repeated codes in stratoschain_events.go into a single function

relay/client/stratoschain_events.go
- qb 722: change attrib name in prepay tx's event to be accordant with chain side
=> fix/qb-722: fix attrib name for prepay tx

cmd/ppd/node.go, example/network/node1/configs/config.yaml, example/network/node2/configs/config.yaml, framework/client/cf/conn.go, framework/core/server.go, pp/event/register_chain.go, pp/serv/serv.go, pp/serv/sys.go, pp/serv/traffic_dump.go, pp/setting/setting.go, relay/stratoschain/rest.go, utils/log.go
1, Track & dump the inbound/outbound volume for all p2p connections with other resources like CPU, Mem, HD infos.
2, Add configure item:  **TrafficLogInterval** , means dump the log in every x seconds
3, Some bug fixed。
=> Feat/Qb-791: Dump pp inbound/outbound traffic

pp/event/transfer_file.go, pp/requests/requests.go
=> QB-898 Fix file backup workflow

framework/client/cf/conn.go, pp/event/get_pplist.go, pp/event/register_chain.go, pp/peers/pp_list.go, pp/peers/reconnect.go, pp/setting/ppinfo.go
- qb-951: fix duplicate nodes in ppList
- qb-951: fix redundant Register and StartMining requests to SP
- qb-953: add todo of conn handshaking
=> fix/qb951: fix dup node in pp list

pp/serv/sys.go
- qb-954: change fmt.print to utils.log
=> fix/qb954: fix monitor log in terminal

pp/event/upload_slice.go, pp/peers/reconnect.go, pp/peers/sp_peers.go
https://qsn.atlassian.net/browse/QB-870
- Don't delete PP from the ppList after a connection disconnects
=> fix/QB-870 Don't delete PP from ppList after disconnect

relay/client/stratoschain_events.go, relay/stratoschain/rest.go, relay/stratoschain/websocket.go, utils/url.go, utils/url_test.go
- qb-962: add compatibility for params in URL to utils.ParseUrl
=> fix/qb962: add param compatibility to parseurl

cmd/ppd/accounts.go, cmd/ppd/main.go
`ppd config accounts --new-p2p-key` to create a new p2p key even exist
=> add new p2p key flag

msg/header/header.go, pp/api/down_progress.go, pp/client/client.go, pp/event/download_slice.go, pp/event/event_handle.go, pp/event/query_file_info.go, pp/file/file.go, pp/peers/sp_peers.go, pp/requests/requests.go, pp/task/download_task.go
Remove gateway pp from the whole downloading workflow
=> QB-963 Remove gateway pp from download workflow

pp/api/frontend/video_stream_template.html
=> Fix - video stream template

pp/event/upload_file.go, pp/task/upload_task.go
Only calculate file crc once during upload
=> Fix - Only calculate file crc once during upload

pp/peers/sp_peers.go, utils/hashring/hashring.go, utils/hashring/weightedhashring.go
- qb1052: change NodeStatus to sync.Map in hashring and weightedhashring
=> fix/qb1052: fix concurrent map writes for hashring

pp/client/client.go, pp/event/heart.go, pp/event/register_to_sp.go, pp/peers/sp_peers.go
- fix/qb1044: fix of random pp crash from latency check while sp is down
=> fix/qb1044: fix of random pp crash from latency check while sp is down

README.md
updated the content for SDS v0.6.0
=> Doc/update README.md for SDS v0.6.0

relay/stratoschain/rest.go
https://qsn.atlassian.net/browse/QB-1112
- Return an error in FetchAccountInfo if the HTTP response code is not 200
- Print the account sequence used when building transactions
=> fix/QB-1112 Fetch account info error handling

pp/peers/reconnect.go
Changed the  frequency of PP connecting to SP. PP will try to connect to all the SP nodes at intervals at  3(minimum), 30, 300, 600(maximum) secs.
=> fix/qb-1110 Change frequency of pp connecting to SP

cmd/ppd/terminal.go
hotfix: added status cmd in terminal help
=> hotfix: added status cmd in terminal help

relay/stratoschain/rest.go
qb1118: add new return field Tokens while query resource node state
=> fix/qb1118: add new return field Tokens while query resource node state

relay/stratoschain/handlers/stratoschain_events.go, relay/types/types.go
- qb-1137: fix stake balance updating after pp got slashed
- qb-1138: fix multiple execution of slashedPP action upon event from pp/slashed/
=> fix/qb-1124: merge status report check and pp slashing

cmd/relayd/config/config-template.yaml, example/network/node1/configs/config.yaml, example/network/node2/configs/config.yaml, example/network/node3/configs/config.yaml, example/network/node4/configs/config.yaml, example/relayd1.yaml, example/relayd2.yaml, example/relayd3.yaml, example/relayd4.yaml, pp/setting/setting.go
=> chore/ update version to 7

README.md
1. added new cmds
2. modified contents
=> doc/update README.md for SDS v0.7.0

README.md
added SPList with all SP nodes
=> doc/update README.md

utils/hashring/hashring.go
https://qsn.atlassian.net/browse/QB-1177
- Minor fix for the hashring total count. Only increment if the node ID didn't already exist
=> fix/QB-1177 Hashring fix total count

cmd/ppd/terminal.go, pp/event/share.go, pp/serv/terminal_cmd.go
https://qsn.atlassian.net/browse/QB-1206
- Rename share expiry to share duration
=> Feat/QB-1206 Minor share message changes 

example/network/node1/configs/config.toml, example/network/node2/configs/config.toml, example/network/node3/configs/config.toml, example/network/node4/configs/config.toml, example/rpcclient/main.go, pp/event/upload_file.go, pp/event/upload_slice.go, pp/file/file_rpc.go, pp/requests/requests.go, pp/serv/account.go, pp/serv/rpc.go, pp/serv/serv.go, pp/setting/setting.go, pp/task/upload_task.go
* rpc server with file uploading related methods
* extends local file operations to remote operations (file.go to file_rpc.go)
* {result: []} in rpc response carries file offset when asking for pieces of data
* handled the limit of rpc request size when a big piece of data is asked 
* a sample client is implemented 
------------------
This is the rpc messages:  
-->  for requests from client;  <-- for response from server.   When the file data is too long, "..." is shown
Example: successful uploading a 12 MB file
-->  {"jsonrpc":"2.0","id":1,"method":"user_requestUpload","params":[{"filename":"12m.test","filesize":11534336,"filehash":"v05ahm55j5jog24t61l9tqfiiu8ovdkhae7ttn5o","walletaddr":"st1macvxhdy33kphmwv7kvvk28hpg0xn7nums5klu","walletpubkey":"stpub1gyhkcs6r8p69vkzcg9pyysm2vu6rjnnwgahh …
=> feat/QB-1198 RPC service and uploading file through RPC

go.mod, go.sum
- qb1220: update go.mod (stchain version)
=> feat/qb-1220: upgrade relayd protobuf

go.mod, go.sum, relay/stratoschain/rest.go
- qb1220: FetchAccountInfo now returns BaseAccount instead of EthAccount
=> fix/qb1220: FetchAccountInfo from stchain now returns BaseAccount instead of EthAccount

relay/types/broadcast.go
- qb1220: fix Unknown msg type [meta_node_registration_vote]
=> fix/qb1220: fix Unknown msg type [meta_node_registration_vote]

pp/api/stream_video.go, pp/requests/requests.go
- qb1220: fix unmarshal ed25519 pubkey
=> fix/qb1220: fix unmarshal ed25519 pubkey

utils/hashring/hashring.go, utils/hashring/weightedhashring.go
https://qsn.atlassian.net/browse/QB-1187
- Add a bit more documentation for the hashring
=> chore/QB-1187 Hashring documentation

pp/event/get_pp_status.go
- qb-1273: Remove the retry for the SPAM checking of pp node status
=> fix/qb1273: Remove the retry for the SPAM checking of pp node status

cmd/ppd/accounts.go, cmd/ppd/config.go, cmd/ppd/node.go, pp/serv/account.go, pp/setting/setting.go, utils/tools.go
=> fix/qb1283: fix ppd cmd toml

framework/client/cf/conn.go, framework/core/conn.go
Increase handshake timeout to 5 seconds
=> chore/ increase handshake timeout

README.md
The Stratos Decentralized Storage (SDS) network is a scalable, reliable, self-balancing elastic acceleration network driven by data traffic. It accesses data efficiently and safely. The user has the full flexibility to store any data regardless of the size and type.
SDS is composed of many resource nodes (also called PP nodes) that store data, and a few meta nodes (also called indexing or SP nodes) that coordinate everything.
The current repository contains the code for resource nodes only. For more information about meta nodes, we will open source it once it's ready.
Here, we provide a concise quickstart guide to help set up and run a SDS resource node. For more details of SDS as well as the Tropos-Incentive-Testnet rewards distribution, please refer to [Tropos Incentive …
=> Update README.md change versions 0.8.1

framework/core/conn.go
This is for sync to https://github.com/stratosnet/sds/pull/231, in order to merge the commit 03062954a864ac5e587b2af698c8d59ced8ac682 into release.
=> feat/QB-1310 sp cpu high rate 

pp/peers/reconnect.go
1,fixed overflow issue
2,doubled retry interval, max at 15 min
Note: pp already have the feature that reconnect different sp after sp disconnect
=> Fix/QB-1345: reconnect PP to a different SP after sp disconnect

utils/hashring/hashring.go
- add disk usage information to node
- add function in hsahring to update node disk usage
=> feat/Qb-1365 pp node disk usage will affect the task assignment for upload/backup

example/network/node1/configs/config.toml, example/network/node2/configs/config.toml, example/network/node3/configs/config.toml, example/network/node4/configs/config.toml, framework/core/tasks.go, metrics/metrics.go, metrics/prom_service.go, pp/event/download_slice.go, pp/event/transfer_file.go, pp/event/upload_slice.go, pp/serv/rpc.go, pp/serv/serv.go, pp/setting/setting.go, pp/task/download_task.go, pp/task/transfer_task.go, pp/task/upload_task.go
- qb1383: add metrics for prometheus in pp
=> feat/qb1383: add metrics for prometheus in pp

pp/event/download_file_wrong.go, pp/event/download_slice.go, pp/event/query_file_info.go
- add more logs to download request signature verification
- fix download retry
=> QB-1410 add log to download signature validation and fix download retry

pp/event/download_slice.go, pp/event/query_file_info.go
- qb1400: adjust log readability of download file and getShareFile
=> fix/qb1400: adjust log readability of download file and getShareFile

framework/client/cf/conn.go, framework/core/timeout.go, pp/api/stream_video.go, pp/event/timeout_handler.go
Fix api and timeout handler that are broken by p2p server being moved to context
=> fix/qb1498 Fix api and timeout handler 

framework/core/conn.go, utils/log.go
https://qsn.atlassian.net/browse/QB-1431
https://qsn.atlassian.net/browse/QB-1432
- fixing two different panics
=> fix/QB-1431 & QB-1432 Fix panics

utils/cache/redis.go
=> fix/qb-1520 DB access error in sp 

example/relayd/node1/relayd.toml, example/relayd/node2/relayd.toml, example/relayd/node3/relayd.toml, example/relayd/node4/relayd.toml, pp/event/maintenance.go
Related PR: [https://github.com/stratosnet/sp/pull/332](https://github.com/stratosnet/sp/pull/332)
=> Fix/QB1545: Node can not go back to the hashring after maintenance

pp/event/share.go
Added "no shared file found" log to `allshare` command when there's no shared file
=> feat/QB-1576 Add log to allshare when no shared file

cmd/ppd/accounts.go, cmd/ppd/config.go, cmd/ppd/node.go, example/network/node1/configs/config.toml, example/network/node2/configs/config.toml, example/network/node3/configs/config.toml, example/network/node4/configs/config.toml, pp/account/account.go, pp/event/get_splist.go, pp/serv/terminal_cmd.go, pp/setting/setting.go, utils/readconfig.go, utils/tools.go
https://qsn.atlassian.net/browse/QB-1564
- setting.SetConfig now properly works with TOML values
- terminal config command now supports other types, not just strings
- removed some useless comments
=> fix/QB-1564 SetConfig TOML support

Makefile, tests/e2e/Dockerfile, tests/e2e/entrypoint.sh
Add `Dockerfile` and `entrypoint.sh` for integration tests.
=> QB-1532 Add Dockerfile for integration test

.github/workflows/pull-request.yml
https://qsn.atlassian.net/browse/QB-1603
- Remove action push trigger
- Specify branches in pull_request trigger instead of push
=> test/QB-1603 Update pull-request action trigger

pp/event/download_slice.go, pp/event/upload_slice.go
=> fix/Qb1650: tiny fix NPE

pp/requests/requests.go, utils/sign.go
=> Revert "feat/QB-1691 taskid slicehash included in report signature"

example/network/node1/configs/config.toml, example/network/node2/configs/config.toml, example/network/node3/configs/config.toml, example/network/node4/configs/config.toml, pp/requests/requests.go, pp/serv/sys.go, pp/setting/setting.go
- qb1772: add soft cap for disk size
=> fix/qb1772: add soft cap for disk size

framework/client/cf/conn.go, framework/core/conn.go
https://qsn.atlassian.net/browse/QB-1777
- Adding a timeout for the read and write loops of the framework client connections
=> feat/QB-1777 framework read/write timeouts

pp/event/report_node_status.go, pp/requests/requests.go
- qb1799: update error handling of status report
=> fix/qb1799: fix disk size

cmd/sdsweb/README.md
https://qsn.atlassian.net/browse/QB-1915
- add README for sdsweb
=> docs/QB-1915 Add sdsweb README

msg/header/header.go, pp/event/clear_expired_share.go, pp/event/event_handle.go
- qb1920: adjust order of MsgType for compatibility
- qb1920: fix clear_exp_share event
=> feat/qb1920: adjust order of MsgType for compatibility

pp/event/clear_expired_share.go, pp/serv/terminal_cmd.go
- qb1920: add detailed rsp info to clear_exp_share
=> feat/qb1920: event permission check

cmd/ppd/ipfs/rootcmd.go, example/rpcclient/rpc_client.go, pp/api/stream_video.go, pp/file/file.go, pp/task/download_task.go, pp/types/peer_list.go
- qb2014: update directory permission to 700, file permission to 600
=> fix/qb2014: update directory permission to 700, file permission to 600

cmd/ppd/ipfs/ipfsapi.go, cmd/ppd/ipfs/rootcmd.go
* fix: ipfs put and get
* fix: first request always fail ---------
=> chore/ipfs fix release v0.10.0 (#456)

pp/event/upload_file.go, pp/file/clear_tmp_files.go, pp/file/video.go, pp/namespace/api.go, pp/serv/serv.go, pp/serv/sys.go
- qb2028: clear tmp files generated during uploads/downloads
=> fix/qb2028: clear tmp files generated during uploads/downloads

framework/core/types.go, pp/event/sys_info.go, pp/file/path.go, pp/setting/constants.go, pp/setting/setting.go, utils/defaults.go
- qb1992: default value adjustment of config items and constants
=> fix/qb1992: default value adjustment of config items and constants

pp/event/upload_slice.go, pp/p2pserver/sp_peers.go
- qb2044: mitigation of autoclean map upon slow upload
=> fix/qb2044: mitigation of autoclean map upon slow upload

pp/task/download_task.go
- qb2064: update autoclean map default thresholds
=> fix/qb2064: update autoclean map default thresholds

cmd/ppd/ipfs/rootcmd.go, example/network/node1/config/config.toml, example/network/node10/config/config.toml, example/network/node11/config/config.toml, example/network/node12/config/config.toml, example/network/node13/config/config.toml, example/network/node14/config/config.toml, example/network/node15/config/config.toml, example/network/node16/config/config.toml, example/network/node2/config/config.toml, example/network/node3/config/config.toml, example/network/node4/config/config.toml, example/network/node5/config/config.toml, example/network/node6/config/config.toml, example/network/node7/config/config.toml, example/network/node8/config/config.toml, example/network/node9/config/config.toml, example/rpcclient/main.go, example/rpcclient/rpc_client.go, pp/api/rpc/types.go, pp/event/get_pp_status.go, pp/namespace/api.go
https://qsn.atlassian.net/browse/QB-2049
- For RPC upload, refresh the reqTime and signature each time new data is sent. This makes sure the request is not expired when actually starting the upload to SP
- Added meta node info to the status command
=> fix/QB-2049 rpc upload refresh reqTime

pp/event/download_slice.go
- qb2067: add meaningful message when download times out
=> fix/qb2067: add meaningful message when download times out

pp/serv/terminal_cmd.go
Fix params length check for update deposit terminal cmd
=> fix/ terminal update deposit params check

cmd/relayd/setting/setting.go, example/network/node1/config/config.toml, example/network/node10/config/config.toml, example/network/node11/config/config.toml, example/network/node12/config/config.toml, example/network/node13/config/config.toml, example/network/node14/config/config.toml, example/network/node15/config/config.toml, example/network/node16/config/config.toml, example/network/node2/config/config.toml, example/network/node3/config/config.toml, example/network/node4/config/config.toml, example/network/node5/config/config.toml, example/network/node6/config/config.toml, example/network/node7/config/config.toml, example/network/node8/config/config.toml, example/network/node9/config/config.toml, example/relayd/node1/config/config.toml, example/relayd/node2/config/config.toml, example/relayd/node3/config/config.toml, example/relayd/node4/config/config.toml, pp/setting/constants.go
=> chore/update version 0.10.2

pp/event/download_slice.go, pp/file/file.go
- qb2144: fix download progress percentage issue and dup log
=> fix/qb2144: fix download progress percentage issue and dup log

pp/event/upload_file.go, pp/serv/terminal_cmd.go
fix putstream expired by shifting generation of reqTime after  pre-upload process
=> fix: pustream expired

pp/event/activate.go
- qb2259: fix-UPDATE_PP_ACTIVATE_STATE
=> feat/qb2259: fix-UPDATE_PP_ACTIVATE_STATE

pp/task/transfer_task.go
https://qsn.atlassian.net/browse/QB-2296
- Add more details to the `failed getting transfer task` error log
=> feat/QB-2296 Add details to failed getting transfer task error

pp/serv/terminal_cmd.go, utils/console/terminal.go
- qb2326: fix whitespace handling in cmd line
=> fix/qb2326: fix whitespace handling in cmd line

framework/client/cf/conn.go, framework/core/conn.go, framework/utils/buffer_pool.go
- qb2407: add debug logs for inbound cost time
=> feat/qb2407: inbound cost time debug

tx-client/grpc/query.go
https://qsn.atlassian.net/browse/QB-2339
- Replace the remaining ozone limit query with a noz supply query, as it contains more data
=> fix/QB-2339 Query noz supply

framework/client/cf/conn.go, framework/core/conn.go, pp/event/download_slice.go, utils/buffer_pool.go
- qb2407: add debug log for cost time
- qb2407: add error log if buffer is not successfully released
- qb2407: remove not meaningful log "add 0 ms" while AddCostTime
=> fixqb2407: add debug log for cost time and buffer pool

framework/utils/buffer_pool.go, pp/requests/requests.go
- st40: check before release buffer
=> fix/st40: check before release buffer

cmd/ppd/terminal.go, pp/serv/terminal_cmd.go
Add flags to ppd cmds which have 2 or more optional params.
Involved cmd: 
prepay, put, putstream, withdraw, updateinfo
=> Feat/ST-202: Update pp cmd

cmd/ppd/terminal.go, pp/serv/terminal_cmd.go
following cmd updated: 
activate, updateDeposit, deactivate, send
=> Fix/ST-202: Add flags to all optional params

example/network/node1/config/config.toml, example/network/node10/config/config.toml, example/network/node11/config/config.toml, example/network/node12/config/config.toml, example/network/node13/config/config.toml, example/network/node14/config/config.toml, example/network/node15/config/config.toml, example/network/node16/config/config.toml, example/network/node2/config/config.toml, example/network/node3/config/config.toml, example/network/node4/config/config.toml, example/network/node5/config/config.toml, example/network/node6/config/config.toml, example/network/node7/config/config.toml, example/network/node8/config/config.toml, example/network/node9/config/config.toml, pp/event/download_file_wrong.go
- don't increase the download progress when receiving a DownloadFileWrong response and we already have the slice (so it's not counted twice)
- update localnet configs to `v0.12.3`
=> fix/ wrong download progress for DownloadFileWrong

framework/crypto/encryption/encryption_test.go, pp/file/file.go, pp/serv/monitor.go, tx-client/types/tx/signing/signature.go
- redoing [this typos PR](https://github.com/stratosnet/sds/pull/718) minus the `flate` changes
=> chore/ typos
