stratosnet/sds

- relay/client/stratoschain_events.go
- relay/stratoschain/rest.go
- relay/stratoschain/websocket.go
- utils/url.go
- utils/url_test.go
https://qsn.atlassian.net/browse/QB-706
- URLs now have default values of http/https for the scheme and 80/443 for port
- No need to specify both https and port 443 at the same time (or http and port 80) in config
- unit tests for URL parsing
> Feat/QB-706 default scheme and port config for URLs

- pp/event/query_file_info.go
We need to send msg to gateway pp to query file storage info to allow the gateway pp store file storage info in its cache. We'll later remove gateway pp from the whole downloading workflow
> Fix - Send msg to gateway pp to query file storage info

- cmd/ppd/accounts.go
- cmd/ppd/config.go
- cmd/ppd/main.go
- cmd/ppd/node.go
- cmd/ppd/terminal.go
- example/network/node1/configs/config.yaml
- example/network/node2/configs/config.yaml
- example/network/node3/configs/config.yaml
- example/network/node4/configs/config.yaml
- pp/api/create_wallet.go
- pp/api/import_wallet.go
- pp/serv/account.go
- pp/serv/terminal_cmd.go
- pp/setting/setting.go
- utils/console/terminal.go
@weichen-qsnetwork this pr includes breaking changes for your scripts on the account creation and config cmd
to create config without interactive key creation
`ppd config`
to create config with interactive key creation 
`ppd config -w -p`
to create wallet key and p2p key
`ppd config accounts  -n wallet2 -p 123 -s` 
@hong-pang please update your document as well
> fix the new wallet cmd in terminal & add accounts cmd to config

- pp/api/stream_video.go
- pp/file/video.go
- use root path to build tmp folder for video upload
- remove the check of restAddress when caching video
> Feat/QB-1098 change video cache file to  sds tmp file instead of os tmp

- pp/event/upload_file.go
1. Added UhfInfo (including FileName and CreateTime) to replace the existing file info for the same uploaded file from different users   
2.  Change the log message when file already exist
> Qb-1088 use different names to upload an existing file

- relay/client/client.go
- relay/stratoschain/handlers/stratoschain_events.go
- relay/stratoschain/rest.go
- relay/types/broadcast.go
https://qsn.atlassian.net/browse/QB-1105
- After a block mode broadcast in relayd, directly call the event handlers
- Add a cache to avoid processing the same event twice
- Fix tx hash processing when dealing with multiple messages in one transaction
- Improve logs when relayd broadcasts txs
- Fix attributes used by slashing event handler
> feat/QB-1105 Block broadcast event handling

- example/network/node1/configs/config.yaml
- example/network/node2/configs/config.yaml
- example/network/node3/configs/config.yaml
- example/network/node4/configs/config.yaml
- utils/hashring/hashring.go
- utils/hashring/hashring_test.go
- utils/hashring/weightedhashring.go
- utils/hashring/weightedhashring_test.go
https://qsn.atlassian.net/browse/QB-1177
- Fix hashring GetNodeExcludedNodeIDs method. There is now a param to specify if the excluded nodes should become offline or not
> fix/QB-1177 Hashring GetNodeExcludedNodeIDs Fix

- pp/api/stream_video.go
- pp/requests/requests.go
- qb1220: remove unnecessary pubkey unmarshaling during sigVerify
> fix/qb1220: remove unnecessary pubkey unmarshaling during sigVerify

- example/rpcclient/Makefile
- example/rpcclient/main.go
- pp/file/file.go
- pp/file/file_rpc.go
- pp/requests/requests.go
- pp/serv/rpc.go
- pp/task/download_task.go
This PR is on top of PR #188 (feat/QB-1198 RPC service and uploading file through RPC). The first commit (d925be21707750ad6fa4ee0f870459815e9d73fc) is from #188. When #188 is merged, this branch will be rebased.
*  extend the RPC server to handle download related messages
*  extend file_rpc to support download related file operations in case of remote file
*  final check in download task after download finishes
* enhance the sample client to support both upload(put) and download(get)
In this PR, parallel remote download is not supported which is in QB-1228.
> feat/QB-1199 RPC download file

- example/rpcclient/Makefile
- example/rpcclient/main.go
- framework/client/cf/conn.go
- pp/api/rpc/rpc_api.go
- pp/api/stream_video.go
- pp/event/download_file_wrong.go
- pp/event/download_slice.go
- pp/event/query_file_info.go
- pp/event/timeout_handler.go
- pp/file/file.go
- pp/file/file_rpc.go
- pp/requests/requests.go
- pp/serv/rpc.go
- pp/serv/terminal_cmd.go
- pp/task/download_task.go
This PR is on top of PR #192 (feat/QB-1199 RPC download file). The first two commits are from #192. When #192 is merged, this branch will be rebased.
* ReqId of the file is used for identifying the download sessions
* LOCAL_REQID is used for local download, and a generated uuid is used for remote download
* keep a map to match slice ReqId to a file
* different way to handle the end of download - no local tem file nor csv file for remote download
* ReqId included in download related message
> feat/QB-1228 parallel download for RPC

- framework/client/cf/conn.go
https://qsn.atlassian.net/browse/QB-1290
- Don't close the handshake channel, so the server won't panic and crash even if there is time-out (channel will get garbage collected anyway)
> Fix/QB-1290 Handshake panic

- pp/serv/monitor.go
fixed the earlier commit for QB-1266:  pp node monitor.
Wrongly used newer version of go and broken the build.
> feat/Qb 1266/ pp node monitor

- framework/core/conn.go
The reason:
When sendCh has been set to "closed" in other goroutines, and there is no packet in this buffered channel, it enters the selected branch(line 593) with the value of ok false. 
Since the value of packet is nil, quickly the control went back to for loop and comes back to the select again. 
The change:
Check the value of ok and adding a break is sufficient to resolve this scenario.
> feat/QB-1310 SP cpu high rate

- pp/file/file_rpc.go
- pp/serv/rpc.go
- GetRemoteFileData() need to be concurrent safe
- blocking comm between file app and rpc server, by select and channel
> fix/QB-1372 rpc interface could take CPU up to 100%

- framework/client/cf/conn.go
- framework/core/codec.go
- framework/core/conn.go
- framework/core/packet.go
- msg/msg.go
- pp/event/download_slice.go
- pp/event/upload_slice.go
- pp/peers/pp.go
- pp/peers/sp_peers.go
- add PacketId to RelayMsgBuf
- use PacketId to store cost time instead of altering new reqId
> fix/QB-1393 terminal log doesn't work after introduced the req_id changes on speed tracking

- pp/event/share.go
- pp/serv/terminal_cmd.go
The line that registers reqId needs to be moved to terminal_cmd.go otherwise the rpc getshared fails
> fix: fix get share file in both terminal and rpc

- pp/serv/rpc.go
In the feature of "refactor peers package", the context was brought to RPC methods. The use of "context.Background" should have been all cleaned. Some of them were missed.
> QB-1482 fix rpc crash

- utils/log.go
Allow creating a std logger without a log file, for running tests.
- when creating a new logger with `enableFile=false`, don't require a valid filepath
> fix/ std logger doesn't need filepath

- cmd/ppd/terminal.go
- cmd/relayd/setting/setting.go
- example/network/node1/configs/config.toml
- example/network/node2/configs/config.toml
- example/network/node3/configs/config.toml
- example/network/node4/configs/config.toml
- pp/event/activate.go
- pp/event/data.go
- pp/event/deactivate.go
- pp/event/prepay.go
- pp/event/update_stake.go
- pp/serv/terminal_cmd.go
- pp/setting/setting.go
- relay/client/client.go
- relay/stratoschain/rest.go
https://qsn.atlassian.net/browse/QB-936
- added automatic gas calculation by calling the tx simulate endpoint on stchain
- relayd always use automatic gas calculation
- pp uses automatic gas calculation if the gas amount isn't specified
- added `gas_adjustment` entry in pp config
- added `blockchain_info.transactions.gas_adjustment` entry in relayd config
- removed the old `BuildTxBytes` method (unused) and minor refactor to transaction building and broadcasting
> Feat/QB-936 Automatic Gas Calculation

- framework/core/server.go
https://qsn.atlassian.net/browse/QB-1551
- Adding a nil check to avoid a panic
> fix/QB-1551 ConnsSize nil pointer

- Dockerfile
- Makefile
- entrypoint.sh
* Use `entrypoint.sh` to update permissions when we mount the folder to the container.
* Update Makefile to easily build docker images.
```
docker build -t sds-rsnode .
docker run -d --name sds-rsnode -p 18081:18081 sds-rsnode
```
You need to confirm that port `18081` is **accessible from the internet**. It is used to communicate with other nodes.
If you want to keeps all configuration and data files outside the container, you can mount a local dir to the container:
```
docker run -d --name sds-rsnode -p 18081:18081 -v ~/sds-rsnode:/sds sds-rsnode
```
The configuration and data files will save to `~/sds-rsnode`.
You may want to interact with SDS resource node via ternimal:
```
docker exec -it sds-rsnode ppd terminal
```
Then you can follow the …
> QB-1793 Update Dockerfile

- relay/stratoschain/tx_builder.go
- [add meaningful error msg while no available account to sign tx](qb1940: add meaningful error msg while no available account to sign tx)
> fix/qb1940: add meaningful error msg while no available account to sign tx

- cmd/ppd/ipfs/rootcmd.go
- example/rpcclient/rpc_client.go
- qb2016: change improperly used filePath to fileName in rpc apis
> fix/qb2016: change improperly used filePath to fileName in rpc apis 

- example/rpcclient/rpc_client.go
- pp/file/file_rpc.go
- qb2018: fix fileHash mismatch issue for tmp file during put/putstream a file using rpc apis
- qb2018: change misused filePath to fileName while uploading file thru rpc apis
> fix/qb2018: fix fileHash mismatch issue during put/putstream a file thru rpc apis

- cmd/ppd/terminal.go
- pp/setting/setting.go
https://qsn.atlassian.net/browse/QB-2039
- removed obsolete login cmd from terminal
- fixed terminal config cmd so it doesn't change the toml comments and formatting after updating a key/value pair
> fix/QB-2039 Remove terminal login cmd

- framework/client/cf/conn.go
- framework/core/conn.go
- framework/core/types.go
- framework/core/utils.go
- pp/p2pserver/client.go
- pp/setting/ppinfo.go
https://qsn.atlassian.net/browse/QB-2100
Merge at the same time as [this SP PR](https://github.com/stratosnet/sp/pull/482)
- Send node IP in first msg during handshake, and use it when creating secondary handshake connection
- Add comment for server `GetRemoteAddr` to warn that it might be the wrong IP when using VMs
> fix/QB-2100 handshake sends node IP in first msg

- pp/event/download_file_wrong.go
- pp/event/download_slice.go
- qb2144： download progress is now updated only after whole slice gets downloaded (vs update by packet), in order to avoid duplicate percentage counts
- qb2144: retrying failedSlices in download_file_fail response will first clear previous DownloadSliceProgress
> fix/qb2144: fix abnormal download progress percentage caused by retrying a download

- pp/api/stream_video.go
- adjust video stream cache order so that header file is cached first and the rests follow segment sequence
- video play only starts after first 2 slices have been cached
> feat: adjust video stream cache order

- framework/utils/defaults.go
- pp/event/sp_maintenance.go
- pp/network/sp_latency.go
- pp/p2pserver/client.go
- pp/p2pserver/pp.go
- pp/p2pserver/reconnect.go
- pp/p2pserver/sp_peers.go
https://qsn.atlassian.net/browse/ST-295
- when the connected SP is under maintenance, connect to others even if there are no optimal candidates (no SP latency check done yet)
- temporarily blacklist SPs that can't be connected to
- increase number of optimal candidates to consider (3 -> 4)
> feat/ST-295 optimize SP reconnection logic

- example/network/node1/config/config.toml
- pp/event/register_to_sp.go
- pp/p2pserver/pp.go
- pp/setting/ppinfo.go
- pp/setting/setting.go
https://qsn.atlassian.net/browse/ST-402
- support domain names as network address by resolving them to an IP address
- added `local_port` config. If not empty, the node will locally listen to this port for new connections
- other nodes will still use `network_port` to connect to this node
- this can be helpful when working with VMs or tunnels/proxies (eg: ngrok)
> feat/ST-402 Domain name support

- framework/utils/hashring/hashring.go
- framework/utils/hashring/hashring_test.go
Fix the hashring panic in RandomNodeExcludedIDs by always testing if the type assertion is ok
> hotfix/ hashring panic in RandomNodeExcludedIDs

- framework/utils/hashring/hashring.go
- framework/utils/hashring/hashring_test.go
- fixed panic in hashring `RemoveNode`, when there are at least 2 online nodes, and `RemoveNode` is called on the last online node in the list
- fixed hashring concurrency issue when reading from internal map
> hotfix/ hashring panic in RemoveNode

- framework/utils/error.go
https://qsn.atlassian.net/browse/ST-762
- fixed `utils.FormatError` so it supports all error types (no matter the type of the root cause)
- added stack trace for the places where `errors.Wrap` is called
- single wrapped error
```
[ERROR] 2025/01/17 13:04:14.156636 playground.go:19: layer one: root  [WRAP](f1|playground.go:45)  [CAUSE](f1|playground.go:43)->(main|playground.go:18)
```
- single wrapped error from other packages
```
[ERROR] 2025/01/17 13:05:59.001364 playground.go:20: layer one: no rows in result set  [CAUSE](f1|playground.go:46)->(main|playground.go:19)
```
- double wrapped error 
```
[ERROR] 2025/01/17 13:05:21.858214 playground.go:19: layer two: layer one: root  [WRAP](f2|playground.go:39)->(f1|playground.go:45) …
```
> fix/ST-762 utils.FormatError support all error types

- pp/p2pserver/reconnect.go
https://qsn.atlassian.net/browse/ST-753
- avoid NPE in `ConfirmOptSP` in certain scenarios (such as reconnecting after waking computer from sleep)
> fix/ST-753 avoid NPE in ConfirmOptSP
